### ISSUE TITLE
can't find the data directory

### ISSUE THREAD

**Issue by wanyao1992** [ShangtongZhang/DeepRL#1]
Hi Shangtong,

Could you tell me how can I create the data directory or where can I download the dataset? Your code can't run successfully without the data data directory. Thanks!

**Comment by ShangtongZhang** [comment]
Thanks a lot for pointing it out. I forgot to mention it. I just updated the README file, please follow the instructions in usage section.

**Comment by wanyao1992** [comment]
Thanks for sharing your code, your code helps me a lot.
