### ISSUE TITLE
Reference for the network design

### ISSUE THREAD

**Issue by tilmto** [ShangtongZhang/DeepRL#100]
Hi,

Thanks for the clean code. I have a question that for the network design (e.g., the [nature body](https://github.com/ShangtongZhang/DeepRL/blob/78df98a8eeccc41dacd952932435a5ecc42e1c67/deep_rl/network/network_bodies.py#L10) as a feature extractor) of the pixel-level games like Atari, do you have any references or you manually design it with your domain knowledge? Thanks!

**Comment by ShangtongZhang** [comment]
It's from the original DQN paper published in Nature.

**Comment by tilmto** [comment]
Got it, thx!
