### ISSUE TITLE
Question about QUOTA-discrete

### ISSUE THREAD

**Issue by yingnan-rl** [ShangtongZhang/DeepRL#102]
Thanks for your code. I think in DeepRL-QUOTA-discrete/deep_rl/agent/BootstrappedNStepQRDQN_agent.py, line 57,58. You normalize the state twice. I can't understand.

**Comment by ShangtongZhang** [comment]
Thanks for pointing this out! It's indeed a bug and I just pushed a fix. I remember the offline evaluation curves were quite weird so I ended up with using online scores. Finally got to know what's wrong....

**Comment by yingnan-rl** [comment]
Never mind, your codes help a lot. By the way, you named your agent and model with "Bootstrappedxxx", does this have anything to do with the article "Deep Exploration via Bootstrapped DQN" ?

**Comment by ShangtongZhang** [comment]
It's kind of option of "boostrapped" q values.

**Comment by yingnan-rl** [comment]
Thanks
