### ISSUE TITLE
Are you speed up the env?

### ISSUE THREAD

**Issue by Ja1r0** [ShangtongZhang/DeepRL#13]
In Atari game env,I found every episode is over soon.And I can't add env.render() to show the game.
(抱歉又留一次言。我发现在atari游戏里，每一个回合都跑得很快。比如Pong这个游戏，虽然一个回合要打满21分，但是还是感觉一秒钟就结束了。请问您是把游戏加速了吗？)

**Comment by ShangtongZhang** [comment]
I don't know how you find it so fast. At least in my machine it's not so fast. Can you show some log?

**Comment by Ja1r0** [comment]
=========log===========
INFO:gym.envs.registration:Making new env: PongNoFrameskip-v4
INFO:gym:episode 1, reward -21.000000, avg reward -21.000000, total steps 994, episode step 994
INFO:gym:episode 2, reward -20.000000, avg reward -20.500000, total steps 1893, episode step 899
INFO:gym:episode 3, reward -21.000000, avg reward -20.666667, total steps 2893, episode step 1000
INFO:gym:episode 4, reward -20.000000, avg reward -20.500000, total steps 3894, episode step 1001
INFO:gym:episode 5, reward -21.000000, avg reward -20.600000, total steps 4803, episode step 909
INFO:gym:episode 6, reward -21.000000, avg reward -20.666667, total steps 5563, episode step 760
INFO:gym:episode 7, reward -20.000000, avg reward -20.571429, total steps 6673, episode step 1110
INFO:gym:episode 8, reward -19.000000, avg reward -20.375000, total steps 7629, episode step 956
INFO:gym:episode 9, reward -18.000000, avg reward -20.111111, total steps 8732, episode step 1103
INFO:gym:episode 10, reward -20.000000, avg reward -20.100000, total steps 9856, episode step 1124
INFO:gym:Testing...
===========================
Each episode takes about 1.5 second.

**Comment by Ja1r0** [comment]
INFO:gym.envs.registration:Making new env: PongNoFrameskip-v4
INFO:gym:episode 1, reward -21.000000, avg reward -21.000000, total steps 994, episode step 994
INFO:gym:episode 2, reward -20.000000, avg reward -20.500000, total steps 1893, episode step 899
INFO:gym:episode 3, reward -21.000000, avg reward -20.666667, total steps 2893, episode step 1000
INFO:gym:episode 4, reward -20.000000, avg reward -20.500000, total steps 3894, episode step 1001
INFO:gym:episode 5, reward -21.000000, avg reward -20.600000, total steps 4803, episode step 909
INFO:gym:episode 6, reward -21.000000, avg reward -20.666667, total steps 5563, episode step 760
INFO:gym:episode 7, reward -20.000000, avg reward -20.571429, total steps 6673, episode step 1110
INFO:gym:episode 8, reward -19.000000, avg reward -20.375000, total steps 7629, episode step 956
INFO:gym:episode 9, reward -18.000000, avg reward -20.111111, total steps 8732, episode step 1103
INFO:gym:episode 10, reward -20.000000, avg reward -20.100000, total steps 9856, episode step 1124
INFO:gym:Testing...    

Each episode takes about 1.5 second.

**Comment by ShangtongZhang** [comment]
It looks good. The episode steps seem in a reasonable scale. And if you don't render the video, it's expected to be fast. And more important, in first 50000 steps there is no training.

**Comment by Ja1r0** [comment]
Thanks,if do not render the game video,the episode will run fast.I don't know this before.
