### ISSUE TITLE
DQN performance on Breakout

### ISSUE THREAD

**Issue by yhcao6** [ShangtongZhang/DeepRL#18]
Hi. Can I ask what is the final score of your DQN implementation and how long it takes to converge?

Thanks!

**Comment by ShangtongZhang** [comment]
For breakout I didn't remember, for pong it takes about 1 night to converge to 21

**Comment by yhcao6** [comment]
Just the approximate score of breakout. Can it over 200 even 300?

Thanks!

**Comment by ShangtongZhang** [comment]
I cannot remember. I haven't run breakout for more than 6 month. Recently I only run Pong for several times.
