### ISSUE TITLE
issue in async_agent.py

### ISSUE THREAD

**Issue by PKU-YYang** [ShangtongZhang/DeepRL#20]
Hi Shangtong:

I was wondering whether here should be: `if i == 0` rather than `if i == config.num_workers`, as in the procs definition the first process is evaluate. 

https://github.com/ShangtongZhang/DeepRL/blob/8224a41ba904cd49dfdb262ab40fd68510c396d0/agent/async_agent.py#L103-L106

**Comment by ShangtongZhang** [comment]
Thanks for pointing it out, you are absolutely right. I just fixed the issue.
