### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by PKU-YYang** [ShangtongZhang/DeepRL#21]
HI Shangtong：

Thanks for making this repository public. I was reading your repository and have two questions, and would really appreciate if you could help give more information.

In the DDPG implementation, you mentioned that the repo you refer to is problematic. Can you please be more specific why that implementation is wrong? As I can see, you have one more line in the actor update which is 

https://github.com/ShangtongZhang/DeepRL/blob/db49a76c5389e71d087734cdfd4f9d20ff7ffbef/agent/DDPG_agent.py#L98 , 

is this the reason?

Also, in the Normalizer function

https://github.com/ShangtongZhang/DeepRL/blob/db49a76c5389e71d087734cdfd4f9d20ff7ffbef/utils/normalizer.py#L9

, they are variables "m", "v", "n", can you pls comment on what they stand for? Thanks.

**Comment by ShangtongZhang** [comment]
I didn't find exactly what was wrong in that repo. But from the experiment results I'm sure there is something wrong.
'm' is mean, 'v' is variance, 'n' is count
