### ISSUE TITLE
P3O_continuous stuck in a loop.

### ISSUE THREAD

**Issue by murtazarang** [ShangtongZhang/DeepRL#28]
The p30 code, seems to be stuck in loop, without any progress.

I think it is at the While True loop, on line 97, in the async_agent.py file. I can't seem to debug that.

Could you please help me with it? Thanks!

**Comment by ShangtongZhang** [comment]
It seems to be some problem with python multiprocessing, I did find this happen sometimes on certain machines but I do not know how to make it work for all the machines. Moreover I will replace all the async methods  with synchronous methods in next major update, so P3O will be out of maintenance.
