### ISSUE TITLE
where to download dataset

### ISSUE THREAD

**Issue by szrlee** [ShangtongZhang/DeepRL#29]
```bash
$ python dataset.py
Traceback (most recent call last):
  File "dataset.py", line 103, in <module>
    generate_dateset(game)
  File "dataset.py", line 67, in generate_dateset
    agent.load(model_file)
  File "/home/xxx/DeepRL/agent/BaseAgent.py", line 21, in load
    state_dict = torch.load(filename, map_location=lambda storage, loc: storage)
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/DQNAgent-vanilla-model-PongNoFrameskip-v4.bin'
```
Thanks for noticing the data directory or where to download this.

**Comment by ShangtongZhang** [comment]
You need to train the model yourself first, then generate the dataset and finally train the action conditional video prediction (ACVP) model. In `dataset.py` there is a `train` function, you need to run that first to get the model (about 12 hours), then use the saved model to generate dataset. And in the latest version of this repo, ACVP hasn't been tested myself yet, so if you find some problem and cannot solve it, you can turn to the previous release. But you still need to train the model yourself. https://github.com/ShangtongZhang/DeepRL/releases/tag/v0.1

**Comment by ShangtongZhang** [comment]
For all other algorithms except ACVP, you do not need this `dataset.py`
