### ISSUE TITLE
continuous a3c

### ISSUE THREAD

**Issue by jingweiz** [ShangtongZhang/DeepRL#3]
Hey,
nice code! you mentioned that sometimes you get nans for training the continuous a3c, maybe you can try to add some weight decay like 1e-4, cos this at least helps me with my implementation, maybe you can also try :)

**Comment by ghost** [comment]
Nice tip :+1:

**Comment by ShangtongZhang** [comment]
Thanks for pointing this out! It makes sense. Hope this can help more people!
