### ISSUE TITLE
Q learning: epsilon-greedy during test phase

### ISSUE THREAD

**Issue by tesslerc** [ShangtongZhang/DeepRL#30]
Hey,

Notice that as opposed to the original implementation, you present the average reward based on the epsilon-greedy policy, however in Q-learning epsilon is added during training and should be set to a small constant during the test phase (5% if I recall correctly).

**Comment by ShangtongZhang** [comment]
Thanks for pointing this out. I did present the online training curve, but nothing prevents the code to recored deterministic test curve.
