### ISSUE TITLE
Segmentation fault when importing on a headless server

### ISSUE THREAD

**Issue by wassname** [ShangtongZhang/DeepRL#32]
I just noticed that it segfaults when used on a headless server. I tried it on an ec2 Deep Learning AMI Image, with ubuntu16.04, python3.6, all requirements.txt same as the file. Meanwhile it worked fine on my desktop. I'm guessing it due to lack of a display, has anyone else experienced this?

I'm logging this as an issue so others know the cause of their segfault may be use on a headless server.

P.S I like how you've packaged DeepRL up

**Comment by ShangtongZhang** [comment]
I also often use it in headless server, although not EC2. I recommend you to try the docker, I think at least it should work.

**Comment by wassname** [comment]
Will do, thanks!
