### ISSUE TITLE
Adding TRPO

### ISSUE THREAD

**Issue by JACKHAHA363** [ShangtongZhang/DeepRL#33]
I know TRPO might get out of fashion because of PPO, but it might worth implementing.

**Comment by ShangtongZhang** [comment]
Yes, but in the near feature I have no plan to implement it. Any contribution is welcomed.

**Comment by Unimax** [comment]
what about TRPPO? :)

**Comment by ShangtongZhang** [comment]
Any contribution is welcomed.
