### ISSUE TITLE
Error in A2C_agent.py?

### ISSUE THREAD

**Issue by ZmeiGorynych** [ShangtongZhang/DeepRL#36]
Thanks a lot for writing this!

In line 51 of A2C_agent.py, we have `next_value = rollout[i + 1][2]`, however in line 42 only the second value is populated for the last row, and in general values are in the second, not third, position in each rollout row - should it be `next_value = rollout[i + 1][1]` ?
That value is never actually used unless self.config.use_gae=True, and use_gae is False in examples.py, could this be why this has gone unnoticed - or am I missing something?

**Comment by ShangtongZhang** [comment]
It's indeed a bug due to the recent frequent iteration of the library. Thanks a lot for pointing this out! Just pushed a fix.
