### ISSUE TITLE
What does torch.cuda.is_available() by itself do?

### ISSUE THREAD

**Issue by kenfehling** [ShangtongZhang/DeepRL#41]
Hi, thanks for this codebase! I've been trying to get familiar with it and I was wondering why `torch.cuda.is_available()` is called in a couple of places:

https://github.com/ShangtongZhang/DeepRL/blob/6f4039914c495a8f0339dc3874e84d128cea7403/deep_rl/agent/BaseAgent.py#L87

https://github.com/ShangtongZhang/DeepRL/blob/6f4039914c495a8f0339dc3874e84d128cea7403/deep_rl/component/replay.py#L60

It seems like this statement should have no effect. Is it some kind of workaround for something?

**Comment by ShangtongZhang** [comment]
Yes, it is a workaround. This function will trigger cuda initialization. I call it to make sure that sub-process will initialize cuda earlier than the main process, which is essential. Otherwise there will be cuda initialization error.

**Comment by kenfehling** [comment]
Ohh ok, thank you!
