### ISSUE TITLE
entropy term in continuous spaces?

### ISSUE THREAD

**Issue by TomLin** [ShangtongZhang/DeepRL#43]
Hello Shangtong, 

Sorry for bothering you, it's more a question of the code clarification instead of an bug issue. I am a bit confused on how you define the entropy in `class GaussianActorCriticNet(nn.Module, BaseNet)`. The final return is **tensor(np.zeros((log_prob.size(0), 1)))** for entropy. Does that mean we just define the entropy term as zeros in this case.

Thanks again for any help.

**Comment by ShangtongZhang** [comment]
I assume a fixed unit variance, which means the entropy is a constant and does not depend on the parameters. So I leave it as 0.

**Comment by TomLin** [comment]
Thanks for the response!!
