### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by Sungtae-Lee** [ShangtongZhang/DeepRL#44]
It seems like the code gets slower epoch by epoch. Is there any way I can fix this? (After exploration steps which is 50000)

**Comment by ShangtongZhang** [comment]
Could you share more details, e.g., logs, GPU/CPU, memory size? Before 50000 steps there is no training, so it should be faster. And for some game maybe it may take more time to render after reaching a certain level, I'm not sure about this. Lack of memory may also be a reason.
