### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by djsaunde** [ShangtongZhang/DeepRL#46]
Hello,

I ran `python examples.py` using `game = 'Breakout'` and `dqn_pixel_atari_game(game)`, and after about 60K steps, I ran out of memory. I have 16Gb of RAM (and a 6Gb NVIDIA 1060), so I'm surprised this happened. Is there an explanation for this? I'm using PyTorch 1.0 preview.

**Comment by ShangtongZhang** [comment]
If you run async replay, I'm sure 16G RAM is not enough. If you run sync replay, 16G RAM should be enough. Also I never tested with pytorch 1.0. What is interesting is that OOM happens so early.

**Comment by djsaunde** [comment]
Weirdly, I'm still having the memory leak problem with `SyncReplay`. I downgraded to `torch=0.4.1`, and got the following error:

```
RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead
```

Is there a specific version of `torch` required?

**Comment by djsaunde** [comment]
Weirdly, I'm still having the memory leak problem with SyncReplay. I also downgraded to `torch=0.4.0`, and had the same problem. I'm running Ubuntu 18.04, btw.

**Comment by ShangtongZhang** [comment]
Try docker
