### ISSUE TITLE
simple question about the episode return curve in README

### ISSUE THREAD

**Issue by deeplearnerJHB** [ShangtongZhang/DeepRL#48]
Your code is very professional an is very helpful for me. Thank you very much! Here, I have a simple question: whether the episode return curve of BreakoutNoFrameskip-v4 in README is the return in eval process rather than the return during training?

**Comment by ShangtongZhang** [comment]
It is training curve.

**Comment by deeplearnerJHB** [comment]
Really? I use your original code about DQN to train the BreakoutNoFrameskip-v4 with 3e7 time steps and get a return (near 110) which is much less than your result (near 390 with 2e7 time steps). Whether you change the hyper-parameters for this environment?

**Comment by ShangtongZhang** [comment]
The return displayed in the terminal is different from real return. In Atari, an agent has many lives, during training each live is treated as an episode and this episode return is displayed in the terminal. However the real return reported in the papers are the sum of rewards over all lives, which are recored in .csv files.

**Comment by deeplearnerJHB** [comment]
I see! Thank you very very very much!
