### ISSUE TITLE
Does DQN on Pong work?

### ISSUE THREAD

**Issue by aviralkumar2907** [ShangtongZhang/DeepRL#49]
Hi,

I ran your code with a DQN on Pong, but it doesn't seem to give returns that anywhere look learned. The returns are almost always -20 or so. This even happens with code directly cloned from your repo and with the same version of pytorch 0.4.0, though I turned on async actor and async memory. Do you know what might be going wrong?

Also, can you attach your pong training curve as a reference? 

Thanks!

For example, this is printed on the terminal and even after 1486000 steps, the returns are too bad: ```2019-01-11 18:39:54,986 - root - INFO: total steps 1486000, returns -20.00/-20.00/-20.00/-20.00 (mean/median/min/max), 259.28 steps/s```

**Comment by ShangtongZhang** [comment]
I don't know what's going on. Can you try Breakout, with the provided Dockerfile if possible? It should work on Pong but I don't have data for Pong for now.

**Comment by aviralkumar2907** [comment]
Tried it again right from scratch. But still Pong doesn't work, can't say for breakout right now, it is running.

**Comment by bywbilly** [comment]
@aviralkumar2907 I think you should look at the log file produced by monitor rather than what printed on the screen. These two are different things. About 3 months ago, I used this code to reproduce the results on Pong successfully, so, I think the code is good.

**Comment by ShangtongZhang** [comment]
![image](https://user-images.githubusercontent.com/6715118/53081425-bed6f800-34f2-11e9-8b6f-352619af8559.png)
Yesterday I rerun DQN in Breakout, it looks good in my side.
