### ISSUE TITLE
Performance tendency of game Breakout is not same as the plot you put on the homepage

### ISSUE THREAD

**Issue by deeplearnerJHB** [ShangtongZhang/DeepRL#50]
Hello, thank you for your contribution again. Till now, some problems still worries me. The figure, as shown in the below, is my training plot by using your code. However, the performance tendency of game Breakout is not same as the plot you put on the homepage. In addition, my training is so slow and I have to use 3e7 rather than 2e7 steps to train it. The cost time of each training with 3e7 steps may be 2 days. I don't know why? 

![2019-01-31 4 15 22](https://user-images.githubusercontent.com/34180259/52040802-7ff8f680-2573-11e9-9071-947ca2db6088.png)

**Comment by ShangtongZhang** [comment]
I have no idea about this for now ..

**Comment by ShangtongZhang** [comment]
![image](https://user-images.githubusercontent.com/6715118/53081335-8a633c00-34f2-11e9-903b-eeec1c84eb80.png)
Recently I worked on some projects and was able to rerun my DQN in Breakout. It looks good in my side.
