### ISSUE TITLE
Docker script running into an error

### ISSUE THREAD

**Issue by typicalTYLER** [ShangtongZhang/DeepRL#51]
After running docker_build.sh it fails at this step. And fails at the same point on rerun.

```
Step 14/33 : COPY ./mjkey.txt /root/.mujoco/mjkey.txt
COPY failed: stat /var/lib/docker/tmp/docker-builder373981879/mjkey.txt: no such file or directory
```

**Comment by ShangtongZhang** [comment]
```mjkey.txt``` is the license for Mujoco. If you don't have this just comment this line out in the Dockerfile. But then you are unable to use Mujoco.

**Comment by typicalTYLER** [comment]
Ah yeah I should've read the Dockerfile, thanks for the help and sorry to bother you!
