### ISSUE TITLE
Does DeepRL support multiple gpus or nn.DataParallel()?

### ISSUE THREAD

**Issue by forhonourlx** [ShangtongZhang/DeepRL#52]
Hi Shangtong,

I wonder whether DeepRL modules could be run on multiple gpus of single machine?
Or could DeepRL modules be easily applied to nn.DataParallel()?

Thanks and waiting for your reply.
Simon

**Comment by ShangtongZhang** [comment]
I don't know. I am not aware of a RL setting where this is necessary.
