### ISSUE TITLE
DQN taking too long to converge

### ISSUE THREAD

**Issue by angerhang** [ShangtongZhang/DeepRL#53]
I am running DQN on 1 GPU but it seems to take more than a few days to converge on Pong. A2C needs about 15 hours to converge on Pong using my current setup. I  am using Python 3.6.5 and I also set `config.async_actor = True` as recommended ;D 

Just trying to understand the run times for different methods as I don't see any benchmark in terms of time for this repo. Two notes from my side:
1. It would be great to have the run time benchmarks on different games using different models.
2. Is my DQN taking way too long than it should? If so, where do you suggest that I can go hunt down the issue? The step per second seems to be on the order of hundreds in the beginning but it gradually decreases to 10-20 steps per second.

**Comment by ShangtongZhang** [comment]
Did you use ``` select_device(0)```?

**Comment by angerhang** [comment]
Oops totally missed changing that line. Should be the cause :D thx for the quick response!
