### ISSUE TITLE
What's the difference of the feature and the pixels?

### ISSUE THREAD

**Issue by Kchu** [ShangtongZhang/DeepRL#57]
Excuse me, I'm a beginner of reinforcement learning, I was recently interested in your QUOTA algorithm, while running your code, I saw feature and pixel, I'd like to know the difference. Also, I didn't find the code about QUOTA, please give me some advice when you are free

**Comment by ShangtongZhang** [comment]
Thanks for your interest.
Pixels are pixels. Feature means state is low dimensional feature instead of pixels.
The code for QUOTA is in QUOTA branches (instead of master) as indicated by the remarks in README.

**Comment by Kchu** [comment]
sorry to bother you , but I couldn't find your code about QUOTA in your project...发自我的华为手机-------- 原始邮件 --------主题：Re: [ShangtongZhang/DeepRL] What's the difference of the feature and the pixels? (#57)发件人：Shangtong Zhang 收件人：ShangtongZhang/DeepRL 抄送：Ryan Chu ,Author Thanks for your interest.
Pixels are pixels. Feature means state is low dimensional feature instead of pixels.
The code for QUOTA is in QUOTA branches (instead of master) as indicated by the remarks in README.

**Comment by ShangtongZhang** [comment]
For some historical reasons they are not named as QUOTA.
As indicated by the README in corresponding branches, 
QUOTA-discrete is at https://github.com/ShangtongZhang/DeepRL/blob/QUOTA-discrete/dist_rl.py#L276
QUOTA-continuous is at https://github.com/ShangtongZhang/DeepRL/blob/QUOTA-continuous/dist-ddpg.py#L125

**Comment by Kchu** [comment]
I see! Thankyou very much!
