### ISSUE TITLE
does it allow to save and load optimizer information in A2CAgent pixel

### ISSUE THREAD

**Issue by fuxianh** [ShangtongZhang/DeepRL#58]
I tried to save agent.network as a model with torch.save(), and succeed but without **optimizer information when I tried to resume training, which is I need**. I tried to save with torch.save({'state_dict':agent.network.state_dict, 'optimizer':agent.optimizer}, path), when I load this kind of model, the code runs into error, meaning  model.load_state_dict() is not employed. The optimization method is RMSprop, Can you help solve this problem, thank you.

**Comment by fuxianh** [comment]
I need the optimizer info when resume training.

**Comment by ShangtongZhang** [comment]
Sorry I don't work on any feature request unless I need it myself.
I believe your requirement is very easy to fulfill once you read the pytorch implementation of RMSProp.

**Comment by fuxianh** [comment]
Thank you very much. I'll try to read that.
