### ISSUE TITLE
can't run last experiments in examples.py

### ISSUE THREAD

**Issue by mehdimashayekhi** [ShangtongZhang/DeepRL#59]
Hi 
Thanks for sharing this. I installed the requirements and running the model on CPU, and I could run the first two experiments in examples.py but I can't run the last one

```
    game = 'BreakoutNoFrameskip-v4'
    dqn_pixel(game=game)
    quantile_regression_dqn_pixel(game=game)
    categorical_dqn_pixel(game=game)
    a2c_pixel(game=game)
    n_step_dqn_pixel(game=game)
    option_critic_pixel(game=game)
    ppo_pixel(game=game)
```
it just freezes here after this message ```2019-05-20 13:19:20,818 - root - INFO: steps 0, 38479853.21 steps/s```

more specifically it freezes in the step function in "baseAgent.py" when running ```return self.__pipe.recv()```; can you please have a look at this?

**Comment by ShangtongZhang** [comment]
You can set ```config.async_actor = False``` and replace ```AsyncReplay``` with ```Replay``` or  just use Docker.

**Comment by mehdimashayekhi** [comment]
thanks
