### ISSUE TITLE
Running your code on the server will appear: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Kchu** [ShangtongZhang/DeepRL#60]
Sorry to bother you, I am getting an error when submitting your code to the server: Segmentation fault (core dumped). There is no problem running on my stand-alone machine. I don't know why, please explain it.

**Comment by ShangtongZhang** [comment]
Did you use Docker?

**Comment by Kchu** [comment]
Sorry, I don't use docker, but our lab's server assigns everyone a virtual machine-like account.

**Comment by ShangtongZhang** [comment]
You should try docker

**Comment by Kchu** [comment]
I've the problem. The Initialization function nn.init.orthogonal_ caused this question. If we use another function like nn.init.xavier_normal_ then there won't be this question and code works fine!

**Comment by Kchu** [comment]
I've found the problem. The Initialization function nn.init.orthogonal_ caused this question. If we use another function like nn.init.xavier_normal_ then there won't be this question and code works fine!
