### ISSUE TITLE
Why "End of Asynchronous Methods"?

### ISSUE THREAD

**Issue by ThyrixYang** [ShangtongZhang/DeepRL#61]
Hi,

You said "asynchronous methods are getting deprecated nowadays". Why are they deprecated now? Could you recommend some papers about this conclusion? Thanks.

**Comment by ShangtongZhang** [comment]
I guess mainly because asynchronous methods are difficult to implement and are not friendly to GPU. If you check papers from recent ICML/NIPS, you can find A3C is rarely used as baselines. People tend to use A2C more.

**Comment by ThyrixYang** [comment]
Thanks for the quick reply.

**Comment by QiXuanWang** [comment]
So what if I would like to use a distributed algorithm running on CPU, what would you suggest?

**Comment by ShangtongZhang** [comment]
I would simulate that distributed algorithm (e.g., A2C) with one single process and start multiple runs in parallel, instead of running a real distributed algorithm occupying multiple CPU cores.
(Of course this is not generally good, but I found with A2C/ N-step DQN and limited CPU cores, this does help)

**Comment by QiXuanWang** [comment]
Thanks for quick reply. But I'm not sure I fully understand.
My usage is that I'll have to collect data on real time with multi-processing(or multiple agent), so a distributed training algorithm could help here. (I thought)

In your A3C (v0.1) implementation, I could see processes are spawned and data is synced. In your latest code, you're using gym process. So do you mean I should write my own distributed code or make a wrapper around A2C? Sorry if it's not related.

**Comment by ShangtongZhang** [comment]
For now there is no distributed training. The A2C here is synchronized distributed data collection  and centralized training if you turn off this flag https://github.com/ShangtongZhang/DeepRL/blob/master/deep_rl/component/envs.py#L157. 
If you want to do distributed training I think you have to hack the code yourself.

**Comment by QiXuanWang** [comment]
Thanks again. That's very helpful.
