### ISSUE TITLE
Random seed is fixed across runs

### ISSUE THREAD

**Issue by rpinsler** [ShangtongZhang/DeepRL#67]
When looping over multiple runs, the random seed is the same across each run. That is because the `Task` class uses the default `seed=np.random.randint(int(1e5))`. This statement is only evaluated *once* when the class is loaded, not every time a task is instantiated. This means that every time we instantiate a Task, the same fixed seed is used. The only randomness comes from the initial evaluation of the default, so every time we start the program another (fixed) seed would be chosen.

One easy way to fix this is to set `seed=None` and then call `seed = np.random.randint(int(1e5)) if seed is None else seed`

**Comment by ShangtongZhang** [comment]
Thanks a lot for pointing this out! Just pushed a fix :)

**Comment by rpinsler** [comment]
Awesome, thanks!
