### ISSUE TITLE
Environments usage permission

### ISSUE THREAD

**Issue by lich14** [ShangtongZhang/DeepRL#75]
Hi, my name is Chenghao Li. I wish to utilize your environment to do some research and submit a paper in ICML 2020. I sincerely hope you can permit us to use your environment. I can highlight your contribution or even add you to our author group. Waiting for your reply.

Sincerely yours

**Comment by ShangtongZhang** [comment]
Thanks for your interest! Of course you can use it. No need to add me as an author. Citing my paper is enough. Good luck!

**Comment by lich14** [comment]
Thanks, our paper has submitted. Hope it can get reviewers' points.
