### ISSUE TITLE
Training using AsyncReplay gets stuck after arounf 50k steps.

### ISSUE THREAD

**Issue by ayooshkathuria** [ShangtongZhang/DeepRL#78]
Whenever I use `AysncReplay` for `replay_fn`, my training gets stuck at around 40-50k steps. I am able to get results using `Replay` and `async_actor = False`, but any idea why the former is causing the training to hang?

Also, will using `AyncReplay` or `Replay` cause difference in performace?

**Comment by ShangtongZhang** [comment]
50K steps is when training starts. 
AsyncReplay is much faster than Replay.
Did you use the Dockerfile provided?
