### ISSUE TITLE
Is there any method to install baselines:8e56dd?

### ISSUE THREAD

**Issue by RushToNeverLand** [ShangtongZhang/DeepRL#79]
Ubuntu 18.04 
Docker build
I can clone baselines to local and can 'git checkout 8e56dd'.
But I cannot build docker from Dockerfile because when running 'RUN pip install git+git://github.com/openai/baselines.git@8e56dd#egg=baselines', there is always a error 'fatal: unable to connect to github.com: github.com[0: 13.229.188.59]: errno=Connection timed out'.
Could you help me verify is that my network problem?(Can you build it?)

**Comment by ShangtongZhang** [comment]
I built it successfully 10 hours ago.
