### ISSUE TITLE
How to plot the result of OC?

### ISSUE THREAD

**Issue by RushToNeverLand** [ShangtongZhang/DeepRL#81]
Sorry, I am a newbie in RL. I have run OptionCriticFeature in Cartpole environment. 
But I haven't seen similar files in named 'XXX.bin' file in 'plot_paper.py', could you give me some advice?
Best Regards.

**Comment by ShangtongZhang** [comment]
You need to get the data for plotting by yourself as I don't have a cartpole plot in any of my paper.
