### ISSUE TITLE
How can I use this package in python 3.7?

### ISSUE THREAD

**Issue by jiang-yuan** [ShangtongZhang/DeepRL#89]
ERROR: Command errored out with exit status 1:
     command: /data/yjiang/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-h_sbxe50/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-h_sbxe50/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ny62cs2y
         cwd: /tmp/pip-req-build-h_sbxe50/
    Complete output (6 lines):
    Please install OpenAI Baselines (commit 8e56dd) and requirement.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-h_sbxe50/setup.py", line 6, in <module>
        raise Exception('Only Python 3.5 and 3.6 are supported')
    Exception: Only Python 3.5 and 3.6 are supported
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ShangtongZhang** [comment]
It should be able to run with python 3.7, though I haven't tested it. You could modify setup.py to remove that constraint.
