### ISSUE TITLE
I want to get the experimental data used to plot, if you are willing to

### ISSUE THREAD

**Issue by THSWind** [ShangtongZhang/DeepRL#92]
Hello,
I see your message saying that you are willing to share data for drawing. So If I didn't misunderstand your means and if you are willing to do, I would like you to provide experimental data of ACE, QUOTA, DAC or COF-PAC on breakout and other games(if you have), I really need it to compare with, I use the game score as a metric. Help me plllz    

mail:
rpchou@163.com
or
revan.ruipengzhou@gmail.com

Thanks

**Comment by ShangtongZhang** [comment]
Thanks for your interest and they are here https://drive.google.com/drive/folders/1IGtcbwCiVhf-YlX7svuLT-D1qGx1bKL3?usp=sharing
As in the paper, only QUOTA is tested on Atari games so for ACE, DAC and COF-PAC I don't have data for Atari games.

**Comment by THSWind** [comment]
@ShangtongZhang Thanks a lot, I got it~SO KIND OF YOU
