### ISSUE TITLE
using target network to calculate last state value

### ISSUE THREAD

**Issue by backpropper** [ShangtongZhang/DeepRL#93]
Is there a reference to why we use a separate target network to calculate the last state value?
https://github.com/ShangtongZhang/DeepRL/blob/19db77206eb65621d0670eccc3a556bba9d5fac3/deep_rl/agent/OptionCritic_agent.py#L88

**Comment by ShangtongZhang** [comment]
No that's an ad-hoc decision.

**Comment by backpropper** [comment]
I see. Did it help reduce variance or something else?

**Comment by ShangtongZhang** [comment]
Not sure. I didn't test the one without target network, just followed DQN

**Comment by backpropper** [comment]
ok thanks!
