### ISSUE TITLE
Asynchronous DQN

### ISSUE THREAD

**Issue by Louis-Bagot** [ShangtongZhang/DeepRL#98]
Hello and thanks a lot for this great repo.
I have never been able to get the AsyncBuffer / Async Actor to work with DQN.
The following experiments are on BreakoutNoFrameskip-v4, using the code as-is for the dqn_pixel function in example.py. I am using a GTX 1080 Ti and 3 CPU cores on my shared resources (cluster).

When using the default parameters: 
- `config.replay_fn = lambda: AsyncReplay(memory_size=int(1e6), batch_size=32)`,
- `config.async_actor = True`,
- `select_device(-1)`, 
I get a performance of about 32.8 steps/s.

However this is a pretty low performance, and it looks like this isn't using my GPU. Since  `select_device(-1)` looks like it asks to use CPUs, I tried switching it up to `select_device(0)`.
However in this case I get an error:
![async_error](https://user-images.githubusercontent.com/19324568/97014593-d0d03000-154a-11eb-8fac-d54698525394.png)
where it looks like we're trying to re-init CUDA in a fork and it doesn't seem to like it.

The thing that worked best for me is then to use a normal Replay memory, turn off the async actor and use a GPU, in which case I reach about 110 steps/s. With Double & Duel Q, this falls to about 95steps/s.

Is there something I'm doing wrong, what could I do to get it to work? 
Thanks in advance for any help.

**Comment by ShangtongZhang** [comment]
Did you use the Docker environment I provided?

**Comment by Louis-Bagot** [comment]
Indeed, I didn't! I had to adapt it to the constraints of my cluster. I mainly stuck to the requirements file.

**Comment by ShangtongZhang** [comment]
That CUDA initialization is quite tricky and does depend on the OS. I know it can fail outside the Docker provided. So I guess to make sure it works you have to use the Docker env.

**Comment by Louis-Bagot** [comment]
Alright, I'll try with minimal changes to the Docker. Thanks!
